name: quantforce
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    # Core Data Science Stack
    - numpy>=1.24.0
    - pandas>=2.0.0
    - scipy>=1.10.0
    
    # Machine Learning & Deep Learning
    - torch>=2.0.0
    - scikit-learn>=1.3.0
    
    # Reinforcement Learning
    - gymnasium>=1.0.0
    - stable-baselines3>=2.0.0
    
    # Financial Data & Portfolio Optimization
    - yfinance>=0.2.0
    - PyPortfolioOpt>=1.5.0
    - pandas-market-calendars>=4.0.0
    - exchange-calendars>=4.0.0
    
    # Optimization & Hyperparameter Tuning
    - optuna>=3.0.0
    - cvxpy>=1.3.0
    
    # Plotting & Visualization (NO tikzplotlib)
    - matplotlib>=3.6.0
    - seaborn>=0.12.0
    - plotly>=5.0.0
    
    # Web & Data Collection
    - requests>=2.28.0
    - beautifulsoup4>=4.11.0
    - ccxt>=4.0.0
    
    # Experiment Tracking & Logging
    - tensorboard>=2.10.0
    - wandb>=0.15.0
    
    # Development & Code Quality
    - black>=23.0.0
    - pytest>=7.0.0
    - tqdm>=4.64.0
    
    # System & Performance
    - psutil>=5.9.0
    - pydantic>=2.0.0
    - pyyaml>=6.0.0
    
    # Technical Analysis
    - ta>=0.10.0
    
    # Data Serialization
    - pyarrow>=10.0.0 